### ISSUE TITLE
State is always Unknown

### ISSUE THREAD

**Issue by Jleagle** [custom-components/places#223]
Just tried to set this component up but can't get it to work.
My entity has lat, long & gps_accuracy set.
Not seeing anything in the logs

![](https://i.imgur.com/VZBEBAA.png)
![](https://i.imgur.com/6wjTWqs.png)

Any ideas? Thanks.

**Comment by Snuffy2** [comment]
Please [enable debug logging](https://github.com/custom-components/places/blob/master/CONTRIBUTING.md#enable-debug-logging-in-home-assistant) and post those. It will hopefully provide more detail about what may be going on.

**Comment by Jleagle** [comment]
```2023-09-10 12:34:21.058 INFO (MainThread) [custom_components.places.sensor] (James) [Init] Places sensor: James
2023-09-10 12:34:21.058 DEBUG (MainThread) [custom_components.places.sensor] (James) [Init] System Locale: ('en_US', 'UTF-8')
2023-09-10 12:34:21.058 DEBUG (MainThread) [custom_components.places.sensor] (James) [Init] System Locale Date Format: %m/%d/%y
2023-09-10 12:34:21.058 DEBUG (MainThread) [custom_components.places.sensor] (James) [Init] HASS TimeZone: Europe/London
2023-09-10 12:34:21.058 DEBUG (MainThread) [custom_components.places.sensor] (James) [Init] entity_id: sensor.james
2023-09-10 12:34:21.058 DEBUG (MainThread) [custom_components.places.sensor] (James) [Init] JSON Filename: places-a8a1b5dc4bd4e9f800484e74056550cb.json
2023-09-10 12:34:21.058 DEBUG (MainThread) [custom_components.places.sensor] (James) [Init] Sensor Attributes Imported from JSON file
2023-09-10 12:34:21.058 INFO (MainThread) [custom_components.places.sensor] (James) [Init] DeviceTracker Entity ID: person.james_eagle
2023-09-10 12:34:21.059 DEBUG (MainThread) [custom_components.places.sensor] (James) [Init] Subscribed to DeviceTracker state change events
2023-09-10 12:34:35.056 INFO (SyncWorker_10) [custom_components.places.sensor] (James) Starting Update...
2023-09-10 12:34:35.056 INFO (SyncWorker_10) [custom_components.places.sensor] (James) Calling update for person.james_eagle due to: Track State Change
2023-09-10 12:34:35.056 DEBUG (SyncWorker_10) [custom_components.places.sensor] (James) GPS Accuracy: 24.0
2023-09-10 12:34:35.056 DEBUG (SyncWorker_10) [custom_components.places.sensor] (James) Previous State: None
2023-09-10 12:34:35.056 DEBUG (SyncWorker_10) [custom_components.places.sensor] (James) Previous last_place_name: None
2023-09-10 12:34:35.056 DEBUG (SyncWorker_10) [custom_components.places.sensor] (James) Previous Place Name is None, keeping prior
2023-09-10 12:34:35.056 DEBUG (SyncWorker_10) [custom_components.places.sensor] (James) last_place_name (Initial): None
2023-09-10 12:34:35.056 DEBUG (SyncWorker_10) [custom_components.places.sensor] (James) DeviceTracker Zone Name: Home
2023-09-10 12:34:35.056 DEBUG (SyncWorker_10) [custom_components.places.sensor] (James) Previous Location: None
2023-09-10 12:34:35.056 DEBUG (SyncWorker_10) [custom_components.places.sensor] (James) Current Location: 50.xx,-1.xx
2023-09-10 12:34:35.056 DEBUG (SyncWorker_10) [custom_components.places.sensor] (James) Home Location: 50.xx,-1.xx
2023-09-10 12:34:35.056 INFO (SyncWorker_10) [custom_components.places.sensor] (James) Distance from home [home]: 0.026 km
2023-09-10 12:34:35.056 INFO (SyncWorker_10) [custom_components.places.sensor] (James) Travel Direction: stationary
2023-09-10 12:34:35.056 INFO (SyncWorker_10) [custom_components.places.sensor] (James) Meters traveled since last update: 0
2023-09-10 12:34:35.056 INFO (SyncWorker_10) [custom_components.places.sensor] (James) Not performing update, distance traveled from last update is less than 10 m (0 m)
2023-09-10 12:34:35.056 DEBUG (SyncWorker_10) [custom_components.places.sensor] (James) Reverting attributes back to before the update started
2023-09-10 12:34:35.056 INFO (SyncWorker_10) [custom_components.places.sensor] (James) End of Update

**Comment by Snuffy2** [comment]
I just released Beta v2.5.1b2 that will hopefully fix your issue.  If you'd like, please give it a try. See [how to enable beta versions for an integration in HACS](https://hacs.xyz/docs/faq/beta/).

**Comment by Jleagle** [comment]
v2.5.1b3 is working for me, thanks.

**Comment by Jleagle** [comment]
After using this for a day now, i think it's still not working. It no longer says Unknown, but it is also not acurate.

The places sensor seems to only show me as at work, even though the entity its coming from has been updating to different places.
My person and places entity:

![](https://i.imgur.com/Ia2SHeH.png)
![](https://i.imgur.com/MqRe4Oy.png)

**Comment by Snuffy2** [comment]
Upgrade to v2.5.1b4 which I released last night. beta 3 wasn't updating correctly, sorry.

**Comment by Snuffy2** [comment]
Fixed in v2.5.1
